apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oqthzz2c0-nodejs 
  janus-idp.io/tekton: oqthzz2c0-nodejs
  backstage.io/kubernetes-id: oqthzz2c0-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oqthzz2c0-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  